/**
 * Generate robots.txt for a project
 * Returns robots.txt content based on project settings
 */

const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY
);

module.exports = async function handler(req, res) {
    if (req.method !== 'GET' && req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    const projectId = req.query.projectId || req.body?.projectId;

    if (!projectId) {
        return res.status(400).json({ error: 'Project ID is required' });
    }

    try {
        // Get project details
        const { data: project, error: projectError } = await supabase
            .from('projects')
            .select('*')
            .eq('id', projectId)
            .single();

        if (projectError || !project) {
            return res.status(404).json({ error: 'Project not found' });
        }

        // Determine the base URL for sitemap
        const baseUrl = project.custom_domain
            ? `https://${project.custom_domain}`
            : project.subdomain
            ? `https://${project.subdomain}.yenze.io`
            : `https://yenze.io/s/${project.public_slug}`;

        // Get SEO settings from project metadata
        const seoSettings = project.seo_metadata?.seo || {};
        const allowCrawling = seoSettings.allow_crawling !== false; // Default to true
        const disallowPaths = seoSettings.disallow_paths || [];

        // Generate robots.txt content
        const robotsTxt = generateRobotsTxt(baseUrl, allowCrawling, disallowPaths);

        // Store in project metadata
        await supabase
            .from('projects')
            .update({
                seo_metadata: {
                    ...(project.seo_metadata || {}),
                    robots_generated: true,
                    robots_generated_at: new Date().toISOString()
                }
            })
            .eq('id', projectId);

        // Return JSON with robots.txt content
        return res.status(200).json({
            success: true,
            robotsTxt: robotsTxt,
            baseUrl: baseUrl
        });

    } catch (error) {
        console.error('Generate robots.txt error:', error);
        return res.status(500).json({ error: 'Failed to generate robots.txt' });
    }
}

/**
 * Generate robots.txt content
 */
function generateRobotsTxt(baseUrl, allowCrawling, disallowPaths = []) {
    let content = '';

    if (allowCrawling) {
        // Allow all bots
        content += 'User-agent: *\n';
        content += 'Allow: /\n\n';

        // Add specific disallow rules if any
        if (disallowPaths.length > 0) {
            disallowPaths.forEach(path => {
                content += `Disallow: ${path}\n`;
            });
            content += '\n';
        }

        // Common disallows
        content += '# Common paths to exclude\n';
        content += 'Disallow: /admin/\n';
        content += 'Disallow: /private/\n';
        content += 'Disallow: /*.json$\n';
        content += 'Disallow: /*?*\n\n';

    } else {
        // Disallow all bots
        content += 'User-agent: *\n';
        content += 'Disallow: /\n\n';
    }

    // Add sitemap reference
    content += `# Sitemap\n`;
    content += `Sitemap: ${baseUrl}/sitemap.xml\n\n`;

    // Add crawl delay for good citizenship
    content += '# Crawl-delay\n';
    content += 'Crawl-delay: 10\n\n';

    // Add common bot-specific rules
    content += '# Bot-specific rules\n';
    content += 'User-agent: Googlebot\n';
    content += 'Allow: /\n\n';

    content += 'User-agent: Bingbot\n';
    content += 'Allow: /\n\n';

    content += '# Social Media Bots\n';
    content += 'User-agent: Twitterbot\n';
    content += 'Allow: /\n\n';

    content += 'User-agent: facebookexternalhit\n';
    content += 'Allow: /\n\n';

    // Footer
    content += `# Generated by YENZE on ${new Date().toISOString().split('T')[0]}\n`;

    return content;
}
